name: Executar Script Agendado

on:
  schedule:
    - cron: "0 9 * * *"  # Agendado para 9h UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Para garantir que o repositório completo seja baixado

      - name: Verificar estrutura de diretórios
        run: ls -R

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Install Playwright browsers (Chromium)
        run: playwright install chromium

      - name: Executar script
        run: python ./codigos/drogariaraia.py

